@echo off
cd %cd%
echo ^<meta http-equiv=^"refresh^" content=^"0.5;url=(究ㄚ_ㄜ)究﹛拂〞〞拂﹛﹛﹛﹛﹛﹛﹛﹛﹛系(ㄚ_ㄜ系).html^"^> > "(究ㄜ_ㄜ)究房〞〞房﹛﹛﹛﹛﹛﹛﹛﹛﹛﹛系(ㄜ_ㄜ系).html"
echo ^<meta http-equiv=^"refresh^" content=^"0.5;url=(究ㄜ_ㄜ)究﹛﹛房〞〞房﹛﹛﹛﹛﹛﹛﹛﹛系(ㄜ_ㄜ系).html^"^> > "(究ㄚ_ㄜ)究﹛拂〞〞拂﹛﹛﹛﹛﹛﹛﹛﹛﹛系(ㄚ_ㄜ系).html"
echo ^<meta http-equiv=^"refresh^" content=^"0.5;url=(究ㄜ_ㄚ)究﹛﹛﹛拂〞〞拂﹛﹛﹛﹛﹛﹛﹛系(ㄜ_ㄚ系).html^"^> > "(究ㄜ_ㄜ)究﹛﹛房〞〞房﹛﹛﹛﹛﹛﹛﹛﹛系(ㄜ_ㄜ系).html"
echo ^<meta http-equiv=^"refresh^" content=^"0.5;url=(究ㄜ_ㄜ)究﹛﹛﹛﹛房〞〞房﹛﹛﹛﹛﹛﹛系(ㄜ_ㄜ系)_.html^"^> > "(究ㄜ_ㄚ)究﹛﹛﹛拂〞〞拂﹛﹛﹛﹛﹛﹛﹛系(ㄜ_ㄚ系).html"
echo ^<meta http-equiv=^"refresh^" content=^"0.5;url=(究ㄚ_ㄜ)究﹛﹛﹛﹛﹛拂〞〞拂﹛﹛﹛﹛﹛系(ㄚ_ㄜ系).html^"^> > "(究ㄜ_ㄜ)究﹛﹛﹛﹛房〞〞房﹛﹛﹛﹛﹛﹛系(ㄜ_ㄜ系)_.html"
echo ^<meta http-equiv=^"refresh^" content=^"0.5;url=(究ㄜ_ㄜ)究﹛﹛﹛﹛﹛﹛房〞〞房﹛﹛﹛﹛系(ㄜ_ㄜ系)_.html^"^> > "(究ㄚ_ㄜ)究﹛﹛﹛﹛﹛拂〞〞拂﹛﹛﹛﹛﹛系(ㄚ_ㄜ系).html"
echo ^<meta http-equiv=^"refresh^" content=^"0.5;url=(究ㄜ_ㄚ)究﹛﹛﹛﹛﹛﹛﹛拂〞〞拂﹛﹛﹛系(ㄜ_ㄚ系).html^"^> > "(究ㄜ_ㄜ)究﹛﹛﹛﹛﹛﹛房〞〞房﹛﹛﹛﹛系(ㄜ_ㄜ系)_.html"
echo ^<meta http-equiv=^"refresh^" content=^"0.5;url=(究ㄜ_ㄜ)究﹛﹛﹛﹛﹛﹛﹛﹛房〞〞房﹛﹛系(ㄜ_ㄜ系)_.html^"^> > "(究ㄜ_ㄚ)究﹛﹛﹛﹛﹛﹛﹛拂〞〞拂﹛﹛﹛系(ㄜ_ㄚ系).html"
echo ^<meta http-equiv=^"refresh^" content=^"0.5;url=(究ㄚ_ㄜ)究﹛﹛﹛﹛﹛﹛﹛﹛﹛拂〞〞拂﹛系(ㄚ_ㄜ系).html^"^> > "(究ㄜ_ㄜ)究﹛﹛﹛﹛﹛﹛﹛﹛房〞〞房﹛﹛系(ㄜ_ㄜ系)_.html"
echo ^<meta http-equiv=^"refresh^" content=^"0.5;url=(究ㄜ_ㄜ)究﹛﹛﹛﹛﹛﹛﹛﹛﹛﹛房〞〞房系(ㄜ_ㄜ系).html^"^> > "(究ㄚ_ㄜ)究﹛﹛﹛﹛﹛﹛﹛﹛﹛拂〞〞拂﹛系(ㄚ_ㄜ系).html"
echo ^<meta http-equiv=^"refresh^" content=^"0.5;url=(究ㄜ_ㄚ)究﹛﹛﹛﹛﹛﹛﹛﹛﹛拂〞〞拂﹛系(ㄜ_ㄚ系).html^"^> > "(究ㄜ_ㄜ)究﹛﹛﹛﹛﹛﹛﹛﹛﹛﹛房〞〞房系(ㄜ_ㄜ系).html"
echo ^<meta http-equiv=^"refresh^" content=^"0.5;url=(究ㄜ_ㄜ)究﹛﹛﹛﹛﹛﹛﹛﹛房〞〞房﹛﹛系(ㄜ_ㄜ系).html^"^> > "(究ㄜ_ㄚ)究﹛﹛﹛﹛﹛﹛﹛﹛﹛拂〞〞拂﹛系(ㄜ_ㄚ系).html"
echo ^<meta http-equiv=^"refresh^" content=^"0.5;url=(究ㄚ_ㄜ)究﹛﹛﹛﹛﹛﹛﹛拂〞〞拂﹛﹛﹛系(ㄚ_ㄜ系).html^"^> > "(究ㄜ_ㄜ)究﹛﹛﹛﹛﹛﹛﹛﹛房〞〞房﹛﹛系(ㄜ_ㄜ系).html"
echo ^<meta http-equiv=^"refresh^" content=^"0.5;url=(究ㄜ_ㄜ)究﹛﹛﹛﹛﹛﹛房〞〞房﹛﹛﹛﹛系(ㄜ_ㄜ系).html^"^> > "(究ㄚ_ㄜ)究﹛﹛﹛﹛﹛﹛﹛拂〞〞拂﹛﹛﹛系(ㄚ_ㄜ系).html"
echo ^<meta http-equiv=^"refresh^" content=^"0.5;url=(究ㄜ_ㄚ)究﹛﹛﹛﹛﹛拂〞〞拂﹛﹛﹛﹛﹛系(ㄜ_ㄚ系).html^"^> > "(究ㄜ_ㄜ)究﹛﹛﹛﹛﹛﹛房〞〞房﹛﹛﹛﹛系(ㄜ_ㄜ系).html"
echo ^<meta http-equiv=^"refresh^" content=^"0.5;url=(究ㄜ_ㄜ)究﹛﹛﹛﹛房〞〞房﹛﹛﹛﹛﹛﹛系(ㄜ_ㄜ系).html^"^> > "(究ㄜ_ㄚ)究﹛﹛﹛﹛﹛拂〞〞拂﹛﹛﹛﹛﹛系(ㄜ_ㄚ系).html"
echo ^<meta http-equiv=^"refresh^" content=^"0.5;url=(究ㄚ_ㄜ)究﹛﹛﹛拂〞〞拂﹛﹛﹛﹛﹛﹛﹛系(ㄚ_ㄜ系).html^"^> > "(究ㄜ_ㄜ)究﹛﹛﹛﹛房〞〞房﹛﹛﹛﹛﹛﹛系(ㄜ_ㄜ系).html"
echo ^<meta http-equiv=^"refresh^" content=^"0.5;url=(究ㄜ_ㄜ)究﹛房〞〞房﹛﹛﹛﹛﹛﹛﹛﹛﹛系(ㄜ_ㄜ系).html^"^> > "(究ㄚ_ㄜ)究﹛﹛﹛拂〞〞拂﹛﹛﹛﹛﹛﹛﹛系(ㄚ_ㄜ系).html"
echo ^<meta http-equiv=^"refresh^" content=^"0.5;url=(究ㄜ_ㄚ)究拂〞〞拂﹛﹛﹛﹛﹛﹛﹛﹛﹛﹛系(ㄜ_ㄚ系).html^"^> > "(究ㄜ_ㄜ)究﹛房〞〞房﹛﹛﹛﹛﹛﹛﹛﹛﹛系(ㄜ_ㄜ系).html"
echo ^<meta http-equiv=^"refresh^" content=^"0.5;url=(究ㄜ_ㄜ)究房〞〞房﹛﹛﹛﹛﹛﹛﹛﹛﹛﹛系(ㄜ_ㄜ系).html^"^> > "(究ㄜ_ㄚ)究拂〞〞拂﹛﹛﹛﹛﹛﹛﹛﹛﹛﹛系(ㄜ_ㄚ系).html"
